import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
const root=path.resolve(import.meta.dirname,'..');const run=(args)=>spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});const data=JSON.parse(fs.readFileSync(path.join(root,'data/registry.json'),'utf8'));
test('canonical validator passes',()=>{const r=run(['scripts/validate.mjs']);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/64 assets/)});
test('generated projections reproduce byte for byte',()=>{const r=run(['scripts/generate.mjs','--check']);assert.equal(r.status,0,r.stderr)});
test('immutable ID manifest matches registry',()=>{const expected=fs.readFileSync(path.join(root,'data/asset-ids.txt'),'utf8').trim().split(/\r?\n/);const actual=data.assets.map(x=>x.asset_id).sort();assert.deepEqual(actual,expected);assert.equal(new Set(actual).size,actual.length)});
test('unsupported verification cannot claim PUBLISHED_VERIFIED',()=>{for(const a of data.assets)if(a.verification.outcome!=='PASS')assert.notEqual(a.status,'PUBLISHED_VERIFIED');const monitor=data.assets.find(x=>x.asset_id==='shar-public.asset.github.public-monitor');assert.equal(monitor.status,'PUBLISHED_VERIFIED');assert.equal(monitor.license,'MIT');assert.equal(monitor.namespace,'SHARProduction/shar-public-monitor')});
test('seven transferred repositories use the SHARProduction namespace',()=>{const slugs=['ai-cgi-routing','commercial-production-standard','production-brief-schema','production-deliverables-taxonomy','shar-production-public-roadmap','shar-public-monitor','subtitle-delivery-checker'];for(const slug of slugs){const a=data.assets.find(x=>x.namespace===`SHARProduction/${slug}`);assert.ok(a,slug);assert.equal(a.public_url,`https://github.com/SHARProduction/${slug}`);assert.equal(a.status,'PUBLISHED_VERIFIED')}});
test('organization assets and static Space carry exact evidence',()=>{for(const id of ['shar-public.asset.github.profile','shar-public.asset.github.public-asset-registry','shar-public.asset.github.tool-factory','shar-public.asset.github.open-tools','shar-public.asset.hf.production-open-tools']){const a=data.assets.find(x=>x.asset_id===id);assert.ok(a,id);assert.equal(a.status,'PUBLISHED_VERIFIED')}assert.deepEqual(data.assets.find(x=>x.asset_id==='shar-public.asset.github.open-tools').version,{kind:'release_tag',value:'v1.5.0'});assert.equal(data.assets.find(x=>x.asset_id==='shar-public.asset.hf.production-open-tools').version.value,'2258c81')});
test('Wave 01 has ten verified repository assets and one verified live deployment',()=>{const repos=data.assets.filter(x=>x.asset_id.startsWith('shar-public.asset.github.wave01.'));assert.equal(repos.length,10);for(const a of repos){assert.equal(a.namespace.startsWith('SHARProduction/'),true);assert.equal(a.license,'MIT');assert.equal(a.status,'PUBLISHED_VERIFIED')}const site=data.assets.find(x=>x.asset_id==='shar-public.asset.web.wave01');assert.equal(site.public_url,'https://shar-production-wave-01.pages.dev/');assert.equal(site.status,'PUBLISHED_VERIFIED')});
test('Wave 02 has ten repositories, an orchestrator and a live deployment',()=>{const repos=data.assets.filter(x=>x.asset_id.startsWith('shar-public.asset.github.wave02.'));assert.equal(repos.length,10);for(const a of repos){assert.equal(a.namespace.startsWith('SHARProduction/'),true);assert.equal(a.license,'MIT');assert.equal(a.status,'PUBLISHED_VERIFIED');assert.match(a.verification.details.join(' '),/v1\.0\.3/)}const site=data.assets.find(x=>x.asset_id==='shar-public.asset.web.wave02');assert.equal(site.public_url,'https://shar-production-wave-02.pages.dev/');assert.equal(site.status,'PUBLISHED_VERIFIED');const orchestrator=data.assets.find(x=>x.asset_id==='shar-public.asset.github.wave02-orchestrator');assert.equal(orchestrator.version.value,'v1.0.0');assert.equal(orchestrator.status,'PUBLISHED_VERIFIED')});
test('Wave 03 has ten repositories, an orchestrator and a live deployment',()=>{const repos=data.assets.filter(x=>x.asset_id.startsWith('shar-public.asset.github.wave03.'));assert.equal(repos.length,10);for(const a of repos){assert.equal(a.namespace.startsWith('SHARProduction/'),true);assert.equal(a.license,'MIT');assert.equal(a.status,'PUBLISHED_VERIFIED')}const site=data.assets.find(x=>x.asset_id==='shar-public.asset.web.wave03');assert.equal(site.public_url,'https://shar-production-wave-03.pages.dev/');assert.equal(site.status,'PUBLISHED_VERIFIED');const orchestrator=data.assets.find(x=>x.asset_id==='shar-public.asset.github.wave03-orchestrator');assert.equal(orchestrator.version.value,'v1.0.1');assert.equal(orchestrator.status,'PUBLISHED_VERIFIED')});
test('all published assets carry complete proof gates',()=>{for(const a of data.assets.filter(x=>x.status==='PUBLISHED_VERIFIED')){assert.equal(a.verification.outcome,'PASS');assert.equal(a.verification.content_checked,true);assert.equal(a.verification.function_checked,true);assert.equal(a.verification.owner_checked,true);assert.equal(a.verification.version_checked,true);assert.match(a.public_url,/^https:\/\//);assert.ok(a.verification.details.length)}});
test('scope excludes unrelated owner repositories',()=>{const urls=data.assets.map(x=>x.public_url).join('\n');for(const name of ['/Kinai','/OMNA','/WOMAN','/posture-mirror','/sgaer','/Shariksai','/vite-react-template'])assert.ok(!urls.includes(name));assert.match(data.scope.excluded.join(' '),/personal GitHub account/)});
test('brand identity is exact on every asset',()=>{for(const a of data.assets){assert.equal(a.owner,'SHAR Production');assert.deepEqual(a.brand,{name:'SHAR Production',website:'https://sharprod.com/'})}});
test('relationships resolve to immutable assets',()=>{const ids=new Set(data.assets.map(x=>x.asset_id));for(const a of data.assets)for(const r of a.relationships)assert.ok(ids.has(r.target),`${a.asset_id} -> ${r.target}`)});
test('no canonical registry URL remains in the personal GitHub namespace',()=>{for(const a of data.assets)assert.doesNotMatch(a.public_url,/github\.com\/Ares3333333\//)});
test('schema requires every evidence and lifecycle field',()=>{const s=JSON.parse(fs.readFileSync(path.join(root,'schema/asset-registry.schema.json')));const required=s.properties.assets.items.required;for(const f of ['asset_id','status','version','verified_at','verification','next_review','relationships','notes'])assert.ok(required.includes(f));assert.equal(s.additionalProperties,false);assert.deepEqual(s.properties.status_definitions.required,['PLANNED','LOCAL_READY','AWAITING_OWNER','SUBMITTED','PUBLISHED_VERIFIED','MEASURED','BLOCKED','REJECTED_WITH_REASON'])});

test('Wave 04 has ten repositories, an orchestrator and a live deployment',()=>{const repos=data.assets.filter(x=>x.asset_id.startsWith('shar-public.asset.github.wave04.'));assert.equal(repos.length,10);for(const a of repos){assert.equal(a.namespace.startsWith('SHARProduction/'),true);assert.equal(a.license,'MIT');assert.equal(a.status,'PUBLISHED_VERIFIED')}const site=data.assets.find(x=>x.asset_id==='shar-public.asset.web.wave04');assert.equal(site.public_url,'https://shar-production-wave-04.pages.dev/');assert.equal(site.status,'PUBLISHED_VERIFIED');const orchestrator=data.assets.find(x=>x.asset_id==='shar-public.asset.github.wave04-orchestrator');assert.equal(orchestrator.version.value,'v1.0.0');assert.equal(orchestrator.status,'PUBLISHED_VERIFIED')});

