import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'data/registry.json'),'utf8'));
const errors=[],add=(ok,msg)=>{if(!ok)errors.push(msg)};
const statuses=['PLANNED','LOCAL_READY','AWAITING_OWNER','SUBMITTED','PUBLISHED_VERIFIED','MEASURED','BLOCKED','REJECTED_WITH_REASON'];
const fields=['asset_id','asset_type','title','title_ru','owner','brand','provider','namespace','public_url','canonical_url','version','visibility','license','status','evidence_class','verified_at','verification_method','verification','languages','relationships','content_summary','notes','next_review'];
add(data.schema_version==='1.0.0','schema_version must be 1.0.0');add(data.registry_id==='SHAR_PUBLIC_ASSET_REGISTRY','registry_id mismatch');add(data.brand?.name==='SHAR Production'&&data.brand?.website==='https://sharprod.com/','brand mismatch');for(const s of statuses)add(typeof data.status_definitions?.[s]==='string',`missing status definition ${s}`);
const ids=new Set();for(const a of data.assets){for(const f of fields)add(Object.hasOwn(a,f),`${a.asset_id||'?'} missing ${f}`);add(/^shar-public\.asset\.[a-z0-9.-]+$/.test(a.asset_id),`${a.asset_id} invalid immutable ID`);add(!ids.has(a.asset_id),`${a.asset_id} duplicate`);ids.add(a.asset_id);add(a.owner==='SHAR Production'&&a.brand?.website==='https://sharprod.com/',`${a.asset_id} brand mismatch`);add(statuses.includes(a.status),`${a.asset_id} invalid status`);add(a.visibility==='public',`${a.asset_id} must be public`);add(/^https:\/\//.test(a.public_url)&&a.canonical_url===a.public_url,`${a.asset_id} URL/canonical mismatch`);add(Boolean(a.version?.kind&&a.version?.value),`${a.asset_id} version unsupported`);add(!Number.isNaN(Date.parse(a.verified_at)),`${a.asset_id} bad verified_at`);add(a.verification?.details?.length>0,`${a.asset_id} missing verification details`);if(a.status==='PUBLISHED_VERIFIED'){add(a.verification.outcome==='PASS',`${a.asset_id} PUBLISHED_VERIFIED requires PASS`);add(a.verification.content_checked&&a.verification.function_checked&&a.verification.owner_checked&&a.verification.version_checked,`${a.asset_id} incomplete published verification`)}if(a.verification.outcome!=='PASS')add(a.status!=='PUBLISHED_VERIFIED',`${a.asset_id} unsupported verification must lower status`);}
add(data.assets.length===64,`expected 64 scoped assets, got ${data.assets.length}`);for(const id of ['shar-public.asset.web.sharprod-home','shar-public.asset.web.wave01','shar-public.asset.web.wave02','shar-public.asset.web.wave03','shar-public.asset.web.wave04','shar-public.asset.mcp.public-knowledge','shar-public.asset.cloudflare.production-brief-browser','shar-public.asset.hf.production-brief-taxonomy','shar-public.asset.hf.production-deliverables-taxonomy','shar-public.asset.github.profile','shar-public.asset.github.public-asset-registry','shar-public.asset.github.tool-factory','shar-public.asset.github.open-tools','shar-public.asset.github.wave02-orchestrator','shar-public.asset.github.wave03-orchestrator','shar-public.asset.github.wave04-orchestrator','shar-public.asset.hf.production-open-tools'])add(ids.has(id),`missing canonical asset ${id}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`valid SHAR_PUBLIC_ASSET_REGISTRY: ${data.assets.length} assets, ${ids.size} immutable IDs`);

